GET http://localhost:5000/users/

################################
POST http://localhost:5000/users/
Content-Type: application/json

{
    "name": "Shruti",
    "password": "Shruti1997"
}

################################
POST http://localhost:5000/login/
Content-Type: application/json

{
    "name": "Shruti",
    "password": "Shruti199sda7"
}

################################
POST http://localhost:5000/login/
Content-Type: application/json

{
    "name": "Shruti",
    "password": "Shruti1997"
}
